var data_en ={
	"sign_comma" : "," ,
	"sign_colon" : ":" ,
	"sign_excalm" : "!" ,
	"msg_language" : "language" ,
	"msg_backreport" : "Feedback Report" ,
	"msg_unsubcribed" : "Unsubcribed" ,
	"msg_cause" : "Cause" ,
	"msg_refused" : "Refused" ,
	"msg_help_sent" : "If you need help, please contact us!" ,
	"msg_explain_sent" : "Here is data form back-end" ,
	"msg_success" : "success" ,
	"ioc_href_index1" : "MainIndex",
	"ioc_href_index2" : "Contact Us",
	"ioc_href_index3" : "About Us",
	"ioc_href_index4" : "Language  ",
	"ioc_href_index5" : "÷–Œƒ",
	"ioc_href_index6" : "English",
	"about_data_001" : "Who Are We",
	"about_data_002" : 'On behalf of our IOTBC team as a physical practice group, as the "Internet + block chain" combined with the concept of the pioneers and advocates, we create objects and objects based on the networking chain network platform and intelligent hardware object interactive platform of the robot of artificial intelligence and the Internet of things based on chain network system support system.',
	"about_data_003" : "Our Team",
	"about_data_004" : "Advantage1",
	"about_data_004_1" : "1Our IOTBC team is the representative of the physical application practice, and we look forward to the excellent and practical you.",
	"about_data_005" : "Advantage2",
	"about_data_005_1" : "2Our IOTBC team is the representative of the physical application practice, and we look forward to the excellent and practical you.",
	"about_data_006" : "Advantage3",
	"about_data_006_1" : "3Our IOTBC team is the representative of the physical application practice, and we look forward to the excellent and practical you.",
	"about_data_007" : "Advantage4",
	"about_data_007_1" : "4Our IOTBC team is the representative of the physical application practice, and we look forward to the excellent and practical you.",
	"about_data_008" : "Advantage5",
	"about_data_008_1" : "5Our IOTBC team is the representative of the physical application practice, and we look forward to the excellent and practical you.",
	"about_data_009" : "Advantage6",
	"about_data_009_1" : "6Our IOTBC team is the representative of the physical application practice, and we look forward to the excellent and practical you.",
	"about_data_010" : "Our Advisor",
	"about_data_011" : "Advantage7",
	"about_data_011_1" : "7Our IOTBC team is the representative of the physical application practice, and we look forward to the excellent and practical you.",
	"about_data_012" : "Advantage8",
	"about_data_012_1" : "8Our IOTBC team is the representative of the physical application practice, and we look forward to the excellent and practical you.",
	"about_data_013" : "Advantage9",
	"about_data_013_1" : "9Our IOTBC team is the representative of the physical application practice, and we look forward to the excellent and practical you.",
	"contact_data_001" : "Application For Cooperation",
	"contact_data_002" : "Join the IOTBC ecology and open a new era of the application of the Internet of things + block chain",
	"contact_data_003" : "Skill Joint",
	"contact_data_004" : "Organization Joint",
	"contact_data_003_1" : "Skill Type",
	"contact_data_003_2" : "Industry",
	"contact_data_003_3" : "Phone Number",
	"contact_data_003_4" : "Email Address",
	"contact_data_003_5" : "Please provide your profile and the cooperation plan with IOTBC",
	"contact_data_009" : "Institution Joint",
	"contact_data_009_1" : "Organization name",
	"contact_data_009_2" : "Industry",
	"contact_data_009_3" : "Phone Number",
	"contact_data_009_4" : "Email Address",
	"contact_data_009_5" : "Please provide your profile and the cooperation plan with IOTBC",
	"contact_data_010" : "Submit",
	"index_data_001" : "To Know And Believe In Everything",
	"index_data_002" : "Trust Exchange , Transaction And Interaction",
	"index_data_003" : "Internet And Block Chain",
	"index_data_003_0" : "Internet of things Block Chain",
	"index_data_003_1" : "We should build a universality and customizable ecosystem that combines everything and everything, and support the trust recognition, trust trading, trust interaction and trust transfer of real society and business",
	"index_data_003_2" : "Application Scene",
	"index_data_003_3" : "The COT collaborative public chain system combines the intelligent hardware scheme of the Internet of things. It provides a scalable value service and efficiency trust support for solving the entity scene pain points and the underlying platform.",
	"index_data_003_4" : "Building all things Trust:",
	"index_data_003_5" : "In the physical based social scenario, the most essential economic state of things and objects is transaction and interaction, and the establishment of truable recognition based on things is the foundation of transaction, interaction and transmission. COT focuses on building a people-oriented and value based ecosystem. All things combine the distributed chain network technology to provide a universal basic platform for the Internet of things intelligent hardware collaboration public chain, so that users can use the value-added services of chain network trust supported by low threshold.",
	"index_data_004" : "White Paper Document",
	"index_data_004_1" : "TELEGRAM",
	"index_data_005" : "Comming Soon Waitting For",
	"index_data_006" : "Solutions And Recommendations",
	"index_data_007" : "Internet Skills API platform",
	"index_data_007_1" : "Provide third party developers with a set of development platform labs with the skills of opening, sharing, testing, assisting, assisting, and deploying tools.",
	"index_data_008" : "Application System of Objects And Objects",
	"index_data_008_1" : "To provide the Internet of things chain cloud server system, to create a Dapp network of Internet of things public chain network system.",
	"index_data_009" : "Digital Intelligent Platform System",
	"index_data_009_1" : "It is composed of intelligent label, intelligent chain network device, and mobile phone APP.",
	"index_data_010" : "Intelligent Hardware Interaction System",
	"index_data_010_1" : "It includes human-computer interaction, intelligent private key, mobile APP and so on. Support people to the single field scenic spot block chain application demand.",
	"index_data_011" : '"Object And Person" Scene Interaction System',
	"index_data_011_1" : "It provides a specific scene of Human-Computer Interaction scenario, deep customization and intelligent, and provides custom specific scene application.",
	"index_data_012" : "Intelligent Robot Development System",
	"index_data_012_1" : "IOTBC is currently doing machine learning and human-computer interface interaction mainly through physical bearing language and images.",
	"index_data_013" : "Our Advantages",
	"index_data_014" : "Compliance",
	"index_data_014_1" : "The signature and intelligent contract of IOTBC are protected by the law of the electronic signature and the law of the contract.",
	"index_data_015" : "Full Support",
	"index_data_015_1" : "Fully support the various transactions and interactions between objects, and to meet the deep customization requirements of the specific business scene",
	"index_data_016" : "Low Access Threshold",
	"index_data_016_1" : "Using IOTBC intelligent hardware chain network system to dock traditional intelligent entity services, the traditional intelligent service can be easily upgraded.",
	"index_data_017" : "Elastic Expansion",
	"index_data_017_1" : "IOTBC supports and compatible with traditional Internet IT systems, using loosely coupled design on the business layer to implement the flexible extension of it",
	"index_data_018" : "Deep Custom Development",
	"index_data_018_1" : "IOTBC has rich experience in practical development of intelligent hardware, and has a professional ability to develop the block chain of the Internet of things",
	"index_data_019" : "",
	"index_data_019_1" : "",
	"index_data_020" : "",
	"main_data_011" : "WeChat Number",
	"main_data_012" : "IOTBC team has rich experience in developing intelligent hardware of IOT (from chip application development to intelligent hardware system project level), and has specialized IOT networking block chain deep vertical application level development capability.",
	"main_data_013" : "‘§¡ÙŒª÷√"
}